config/routes.rb
Rails.application.routes.draw do

  resources :lessons

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get  'static_pages/contact'

  get "signup" => "users#new"

  get "login" => "sessions#new"

  post "login" => "sessions#create"

  delete "logout" => "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>

  <nav>
	<ul>
	  <li><%= link_to t("menu.about"), static_pages_about_path %></li>
	  <li><%= link_to t("menu.contact"), static_pages_contact_path %></li>
    <li>framgia</li>
    <li>framgia</li>
	  <li><a href="http://news.railstutorial.org/">News</a></li>
	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
  <%= link_to "MyBlog", root_path, id: "logo"%>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to t("menu.home"), root_path %></li>
        <li><%= link_to t("menu.help"), static_pages_help_path %></li>
        <li><%= link_to t("menu.users"), users_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <div class="menu_avartar">
                  <%= gravartar_for current_user %>
                  <%= t("menu.acount") %><span class="caret"></span>
                </div>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("menu.profile"), user_path(current_user.id) %></li>
                <li><%= link_to t("menu.setting"), edit_user_path(current_user)%></li>
                <li><%= link_to t("menu.logout"), logout_path, method: "delete" %></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to signup_path do %>
                <span class="glyphicon glyphicon-user"> </span>_<%= t("menu.signup") %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <span class="glyphicon glyphicon-log-in"> </span>_<%= t("menu.login") %>
              <% end %>
            </li>
        <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
     'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="banner">
      <%= image_tag "banner.jpg"%>
    </div>
    <%= render "layouts/header" %>
  		<div class="container">
        <% if flash[:success] %>
          <p class="alert alert-success"><%= flash[:success] %></p>
        <% end %>
        <% if flash[:danger] %>
          <p class="alert alert-danger"><%= flash[:danger] %></p>
        <% end %>


		    <%= yield %>
        <%= render "layouts/footer" %>
       <%= debug(params) if Rails.env.development? %>
  		</div>
  </body>
</html>